config/routes.rb
Basecamp::Application.routes.draw do
  root :to => "projects#index"

  resources :users, :only => [:index, :create, :new, :update]

  resources :projects, :only => [:index, :create, :destroy, :update] do
    resources :user_projects, :only => [:create]
    resources :task_lists, :only => [:create]
  end

  resources :task_lists, :only => [:index, :destroy, :update] do
    resources :tasks, :only => [:create]
  end

  resources :tasks, :only => [:index, :destroy, :update] do
    resources :comments, :only => [:create]
    resources :subtasks, :only => [:create]
  end

  resources :subtasks, :only => [:index, :destroy, :update]

  resource :session, :only => [:new, :create, :destroy]
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base

  attr_accessible :password, :username, :display_name,
                  :project_view, :email, :avatar
  attr_reader :password

  validates :email, :uniqueness => true
  validates :email, :password_digest, :presence => true
  validates :password, :length => { :minimum => 3 }

  has_many :user_projects,
    class_name: "UserProject",
    foreign_key: :user_id

  has_many :projects,
    through: :user_projects,
    source: :project

  has_many :assigned_tasks,
    class_name: "Task",
    foreign_key: :assignee_id

  has_attached_file :avatar

  def password
    @password || self.password_digest
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def verify_password(password)
    BCrypt::Password.new(self.password_digest) == password
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :redirect_logged_in_user, :only => [:new]

  def create
    @user = User.new(params[:user])

    if @user.save
      login_user(@user)
      AuthMailer.signup_email(@user).deliver!
      redirect_to root_url
    else
      flash.now[:errors] ||= []
      flash.how[:errors] << @user.errors.full_messages.to_sentence
      render :new
    end
  end

  def new
    render :new
  end

  def update
    @user = current_user
    p params
    @user.update_attributes(params[:user])
    redirect_to root_url
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<div class="col-md-4"></div>
<div class="col-md-3">
  <h2>Fnsh <span class="glyphicon glyphicon-ok main-blue"></span></h2>
  <p>Pave your way to awesome productivity!</p>
  <form action="/users" method="post" role="form">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <div class="form-group">
      <label for="email">Email:</label> <br>
      <input type="text" name="user[email]" id="email" class="form-control" placeholder="you@awesome.com" >
    </div>
    <div class="form-group">
      <label for="password">Password:</label> <br>
      <input type="password" name="user[password]" id="password" class="form-control" placeholder="Password">
    </div>
    <div class="form-group">
      <label for="display-name">Name:</label> <br>
      <input type="text" name="user[display_name]" id="display-name" class="form-control" placeholder="Your full name">
    </div>
    <div class="form-group">
      <input type="submit" value="Sign up" class="btn btn-primary btn-small" />
    </div>
    <p>
    Already have an account? <%= link_to "Login here.", new_session_path %>
    </p>
    <p>
    Made by <a href="http://adlersantos.com">Adler Santos</a>
    </p>
  </form>
</div>
<div class="col-md-4"></div>