config/routes.rb
Basecamp::Application.routes.draw do
  root :to => "projects#index"

  resources :users, :only => [:index, :create, :new, :update]

  resources :projects, :only => [:index, :create, :destroy, :update] do
    resources :user_projects, :only => [:create]
    resources :task_lists, :only => [:create]
  end

  resources :task_lists, :only => [:index, :destroy, :update] do
    resources :tasks, :only => [:create]
  end

  resources :tasks, :only => [:index, :destroy, :update] do
    resources :comments, :only => [:create]
    resources :subtasks, :only => [:create]
  end

  resources :subtasks, :only => [:index, :destroy, :update]

  resource :session, :only => [:new, :create, :destroy]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :author_id, :body, :task_id

  validates :author_id, :body, :task_id, :presence => true

  belongs_to :task,
    class_name: "Task",
    foreign_key: :task_id

  belongs_to :author,
    class_name: "User",
    foreign_key: :author_id
end

app/models/project.rb
class Project < ActiveRecord::Base

  attr_accessible :name, :description, :users

  validates :name, :presence => true

  has_many :user_projects,
    class_name: "UserProject",
    foreign_key: :project_id

  has_many :users,
    through: :user_projects,
    source: :user

  has_many :task_lists,
    class_name: "TaskList",
    foreign_key: :project_id
end

app/models/subtask.rb
class Subtask < ActiveRecord::Base
  attr_accessible :finished, :name, :task_id

  belongs_to :task,
    class_name: "Task",
    foreign_key: :task_id
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :finished, :name, :description, :task_list_id, :assignee_id, :due_date, :position

  belongs_to :task_list,
    class_name: "TaskList",
    foreign_key: :task_list_id

  delegate :project,
    to: :task_list,
    allow_nil: true

  belongs_to :assignee,
    class_name: "User",
    foreign_key: :assignee_id

  has_many :comments,
    class_name: "Comment",
    foreign_key: :task_id

  has_many :subtasks,
    class_name: "Subtask",
    foreign_key: :task_id
end

app/models/task_list.rb
class TaskList < ActiveRecord::Base
  attr_accessible :project_id, :title, :position

  validates :project_id, :presence => true

  belongs_to :project,
    class_name: "Project",
    foreign_key: :project_id

  has_many :tasks,
    class_name: "Task",
    foreign_key: :task_list_id
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base

  attr_accessible :password, :username, :display_name,
                  :project_view, :email, :avatar
  attr_reader :password

  validates :email, :uniqueness => true
  validates :email, :password_digest, :presence => true
  validates :password, :length => { :minimum => 3 }

  has_many :user_projects,
    class_name: "UserProject",
    foreign_key: :user_id

  has_many :projects,
    through: :user_projects,
    source: :project

  has_many :assigned_tasks,
    class_name: "Task",
    foreign_key: :assignee_id

  has_attached_file :avatar

  def password
    @password || self.password_digest
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def verify_password(password)
    BCrypt::Password.new(self.password_digest) == password
  end
end

app/models/user_project.rb
class UserProject < ActiveRecord::Base

  attr_accessible :project_id, :user_id

  belongs_to :project,
    class_name: "Project",
    foreign_key: :project_id

  belongs_to :user,
    class_name: "User",
    foreign_key: :user_id
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(params[:comment])
    @comment.author_id = current_user.id

    if @comment.save
      respond_to do |format|
        format.html { render 'show.rabl' }
        format.json { render 'show.rabl' }
      end
    else
      flash[:errors] ||= []
      flash[:errors] << "Task creation failed, please try again."
      render :back
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :authenticate_user, :only => [:index]

  def create
    ActiveRecord::Base.transaction do
      @project = Project.new(params[:project])

      if @project.save
        @user_project = UserProject.new(user_id: current_user.id,
                                        project_id: @project.id)
        @user_project.save
      else
        flash[:errors] ||= []
        flash[:errors] << "Something went wrong, please try again."
        render :back
      end
    end

    if @project.save
      respond_to do |format|
        format.html { render 'index.rabl' }
        format.json { render 'index.rabl' }
      end
    end
  end

  def destroy
    @project = Project.find(params[:id])
    user_project = UserProject.where("project_id = ? AND user_id = ?",
                                      @project.id,
                                      current_user.id).first
    user_project.destroy

    user_projects = UserProject.where("project_id = ?", @project.id)
    @project.destroy if (user_projects.size == 0)

    respond_to do |format|
      format.html { render 'index.rabl' }
      format.json { render 'index.rabl' }
    end
  end

  def index
    @user = current_user
    @projects = Project.all

    respond_to do |format|
      format.html { render 'index.rabl' }
      format.json { render 'index.rabl' }
    end
  end

  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html { render 'show.rabl' }
      format.json { render 'show.rabl' }
    end
  end

  def update
    @project = Project.find(params[:id])
    @project.update_attributes(params[:project])

    respond_to do |format|
      format.html { render 'show.rabl' }
      format.json { render 'show.rabl' }
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def create
    @task = Task.new(params[:task])
    @task.finished = false
    @task.task_list_id = params[:task_list_id]

    last_task_list = Task.where("task_list_id = ?", params[:task_list_id])
                              .order('position').last

    if last_task_list
      @task.position = last_task_list.position + 1.0
    else
      @task.position = 1.0
    end

    if @task.save
      respond_to do |format|
        format.html { render 'show.rabl' }
        format.json { render 'show.rabl' }
      end
    else
      flash[:errors] ||= []
      flash[:errors] << "Task creation failed, please try again."
      render :back
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    @tasks = Task.all

    respond_to do |format|
      format.html { render 'index.rabl' }
      format.json { render 'index.rabl' }
    end
  end

  def index
    @tasks = Task.all.select{ |task| task.project != nil }
    respond_to do |format|
      format.html { render 'index.rabl' }
      format.json { render 'index.rabl' }
    end
  end

  def update
    @task = Task.find(params[:id])
    @task.update_attributes(params[:task])

    respond_to do |format|
      format.html { render 'show.rabl' }
      format.json { render 'show.rabl' }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :redirect_logged_in_user, :only => [:new]

  def create
    @user = User.new(params[:user])

    if @user.save
      login_user(@user)
      AuthMailer.signup_email(@user).deliver!
      redirect_to root_url
    else
      flash.now[:errors] ||= []
      flash.how[:errors] << @user.errors.full_messages.to_sentence
      render :new
    end
  end

  def new
    render :new
  end

  def update
    @user = current_user
    p params
    @user.update_attributes(params[:user])
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def login_user(user)
    token = SecureRandom.base64(16)

    user.session_token = token
    session[:session_token] = token
    user.save
  end

  def logout_user
    token = SecureRandom.base64(12)
    current_user.session_token = token
    session[:session_token] = nil
    current_user.save
  end
end

app/helpers/subtasks_helper.rb
module SubtasksHelper
end

app/helpers/task_lists_helper.rb
module TaskListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/user_projects_helper.rb
module UserProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fnsh</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <% if current_user %>
      <div class="row mt-10">
        <div class="col-md-5">
          <div class="row">
            You are logged in as <strong><%= current_user.display_name %></strong>
          </div>
          <div class="row">
            <a data-toggle="modal" href="#myModal" class="btn btn-primary btn-xs">Account Settings</a>
            <%= button_to "Logout", session_path, :method => "delete",
                                                  :class => "btn btn-primary btn-xs pull-right" %>
          </div>
        </div> <br>


        <div class="errors">
          <% flash[:errors].try(:each) do |error| %>
            <%= error %>
          <% end %>
        </div> <br>
      </div>

      <hr id="first-hr">

      <div class="row">
        <div class="projects col-md-3"></div>
        <div class="col-md-1 col-divider"></div>

        <div class="project col-md-5"></div>

        <div class="task-detail col-md-3">
        </div>

      </div>

      <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h4 class="modal-title">Account Settings</h4>
            </div>
            <div class="modal-body">

              <form action="<%= user_url(current_user) %>" method="post" role="form" enctype="multipart/form-data">
              <div class="row">
                <div class="col-md-6">
                    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                    <input type="hidden" name="_method" value="put">
                    <div class="form-group">
                      <label for="avatar">Display Image:</label> <br>
                      <% if current_user.avatar %>
                        <%= image_tag current_user.avatar.url, size: "50x50" %>
                      <% else %>
                        <span class="glyphicon glyphicon-user"></span>
                      <% end %>
                      <input type="file" name="user[avatar]" id="avatar" onchange="handle_files(this.files)" style="margin-top:10px;">
                    </div>
                    <div class="form-group">
                      <label for="email">Email:</label> <br>
                      <input type="text" name="user[email]" id="email" class="form-control" value="<%= current_user.email %>" disabled>
                    </div>
                    <div class="form-group">
                      <label for="display-name">Name:</label> <br>
                      <input type="text" name="user[display_name]" id="display-name" class="form-control" value="<%= current_user.display_name %>">
                    </div>
                </div>
              </div>
            </div>
            <div class="modal-footer">
              <input type="submit" class="btn btn-primary", value="Update">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
            </form>

          </div>
        </div>
      </div>

    <% else %>
      <div class="row">
        <%= yield %>
      </div>
    <% end %>
  </div>
</body>
</html>

<script>
  $(document).ready(function () {
    var currentUserJson = <%= current_user.to_json.html_safe %>;

    BC.initialize(currentUserJson);

    function handle_files(files) {
      var file = files[0];
      var reader = new FileReader();
      reader.onload = function(e) {
        console.log(this.result);
      }
      reader.readAsDataURL(file);
    }
  });
</script>